### ISSUE TITLE
The smallest rank supported is 16？

### ISSUE THREAD

**Issue by jcao-ai** [punica-ai/punica#17]
Hi, grateful for this nice work.

Confused that it seems only rank of 16, 32, 64 is supported right now?  [ref](https://github.com/punica-ai/punica/blob/48fd442fb2a121143527b86613851be76c763fac/csrc/sgmv_flashinfer/sgmv_config.h#L10)

**Comment by abcdabcd987** [comment]
Correct. Would you mind clarify your use case? I'm interested to learn.

**Comment by jcao-ai** [comment]
> Correct. Would you mind clarify your use case? I'm interested to learn.

Thanks for you quick response. Actually we are interested in serving lora adapters with variant number of ranks, ranging from 8 to 128 at the same time.  BTW, your code implementation is quite neat and good.

**Comment by jcao-ai** [comment]
@abcdabcd987 
Thanks a lot for your explanation. Padding adapters into the same shape is indeed a workaround. I will take a try soon.

Further more, I got a question about `BGMV` and `SGMV`. Since there goes another project named `S-LoRA` which is based on this project and they seem to keep on the `BGMV` pattern and they declare quite good performance on throughput.

Which pattern/path do you think is better for production deployment? Thanks again.

**Comment by abcdabcd987** [comment]
BGMV is our first attempt on multi-LoRA serving, which assumes each input is for a different model. Although it was already a very good fit for this particular use case, we identified that BGMV has limitations and there are some other opportunities:
1. Using BGMV for prefill is inefficient.
2. The BGMV speed up primarily comes from utilizing more compute units on batched small computes. This free lunch has a limit. 
3. I believe there are use cases in the decode stage where multiple inputs map to the same LoRA models. For example, `AAABCC` is a batch of size 6, but with only 3 LoRA models. When such sharing exists, the speed up comes from one more dimension, i.e., increasing arithmetic intensity (Figure 7 in our paper). As such, the free lunch can go to even higher batch size (Figure 8 and 9).

That's why we created SGMV kernel. BGMV semantics is a strict subset of SGMV. And @yzh119 found a few cool tricks such that SGMV runs faster than BGMV even in the same semantics. Even if your use case is 100% BGMV semantics, we'd still recommend use SGMV. Just treat it as a faster and better-API version of SGMV. I'll do some benchmarks to clear the confusion.

I'm very glad that our [idea](https://le.qun.ch/en/blog/2023/09/11/multi-lora-potentials/) and early implementation got recognized by the research community. Our early version was open sourced on 9/11. While we keep developing actively, we didn't push new commits to the OSS repo since 9/16. After we submitted the paper and cleaned up the code a little bit, we pushed latest versions on 11/2 (#1).
