### ISSUE TITLE
Confusion about offset += 8

### ISSUE THREAD

**Issue by carryyu** [punica-ai/punica#41]
Thanks for your great work!

When I looked at the implementation of the sgmv_flashinfer version, I was very confused about offset += 8. In my understanding, should it be offset += 4?

https://github.com/punica-ai/punica/blob/master/csrc/sgmv_flashinfer/sgmv_flashinfer.cuh#L69
https://github.com/punica-ai/punica/blob/master/csrc/sgmv_flashinfer/sgmv_flashinfer.cuh#L116

Looking forward to your answer.

**Comment by yzh119** [comment]
Hi @carryyu , this is because of the crosswise xor-permuted shared memory layout used in the kernel:

https://github.com/flashinfer-ai/flashinfer/blob/89a761fc31b795f6d6dd021498dced8bc75db44d/include/flashinfer/permuted_smem.cuh#L59-L61

You can check [this slide](https://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21745-developing-cuda-kernels-to-push-tensor-cores-to-the-absolute-limit-on-nvidia-a100.pdf) for more details (page 39-43).

**Comment by carryyu** [comment]
谢谢，已收到！

**Comment by carryyu** [comment]
> Hi @carryyu , this is because of the crosswise xor-permuted shared memory layout used in the kernel:
> 
> https://github.com/flashinfer-ai/flashinfer/blob/89a761fc31b795f6d6dd021498dced8bc75db44d/include/flashinfer/permuted_smem.cuh#L59-L61
> 
> You can check [this slide](https://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21745-developing-cuda-kernels-to-push-tensor-cores-to-the-absolute-limit-on-nvidia-a100.pdf) for more details (page 39-43).

Thanks very much for your reply!
